# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install geojson
  - pip install coveralls
  - pip install nose
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package motionless

after_success:
  - coveralls
